### ISSUE TITLE
Release 1.2 alpha 6

### ISSUE THREAD

**Issue by asomers** [openbsm/openbsm#48]
It would be good to make a new release in time for inclusion into FreeBSD 12.0.  Only 7 days are left!  The following open issues should be fixed first
- [ ] #44 "Got unknown trigger 48" when expiring multiple files at the same time
- [ ] #46 Fix alignment errors in libbsm's print_arb_tok
- [ ] #45 Fix "Got unknown trigger" warning after invoking audit_warn
- [ ] #43 Const correctness
- [ ] #33 Fix CPU spinning issue with empty trail and make -p option the default behaviour

**Comment by cemeyer** [comment]
#43 and #46 are ready to go, I think.

**Comment by asomers** [comment]
ping @csjayp @emaste could we please merge the linked PRs and also publish a new release?

**Comment by csjayp** [comment]
I can have a look.

**Comment by asomers** [comment]
ping @csjayp @emaste can we make the new release?
